name: nlp
channels:
  - defaults
dependencies:
  - python=3.8
  - torchvision
  - pytorch
  - cudatoolkit=10.2
  - torchaudio
  - notebook
  - ipython
  - matplotlib
  - pylint
  - autopep8
  - rope
  - scipy
